/**
 * @file lv_conf.h
 * Configuración de LVGL para ESP32-C6
 */

#ifndef LV_CONF_H
#define LV_CONF_H

#define LV_HOR_RES_MAX (410)
#define LV_VER_RES_MAX (502)

#define LV_COLOR_DEPTH 16

#define LV_USE_LOG 1
#define LV_LOG_LEVEL LV_LOG_LEVEL_WARN

#define LV_USE_ASSERT_NULL 1
#define LV_USE_ASSERT_MALLOC 1
#define LV_USE_ASSERT_STYLE 0
#define LV_USE_ASSERT_MEM_INTEGRITY 0

#define LV_FONT_ROBOTO_12 0
#define LV_FONT_ROBOTO_16 0
#define LV_FONT_ROBOTO_22 0
#define LV_FONT_ROBOTO_28 0
#define LV_FONT_MONTSERRAT_12 0
#define LV_FONT_MONTSERRAT_14 0
#define LV_FONT_MONTSERRAT_16 0
#define LV_FONT_MONTSERRAT_18 0
#define LV_FONT_MONTSERRAT_20 0
#define LV_FONT_MONTSERRAT_22 0
#define LV_FONT_MONTSERRAT_24 0
#define LV_FONT_MONTSERRAT_26 0
#define LV_FONT_MONTSERRAT_28 0
#define LV_FONT_MONTSERRAT_30 0
#define LV_FONT_MONTSERRAT_32 0
#define LV_FONT_MONTSERRAT_34 0
#define LV_FONT_MONTSERRAT_36 0
#define LV_FONT_MONTSERRAT_38 0
#define LV_FONT_MONTSERRAT_40 0
#define LV_FONT_MONTSERRAT_42 0
#define LV_FONT_MONTSERRAT_44 0
#define LV_FONT_MONTSERRAT_46 0
#define LV_FONT_MONTSERRAT_48 1

#define LV_FONT_CUSTOM_DECLARE

#define LV_IMG_CF_INDEXED 0
#define LV_IMG_CF_ALPHA 0

#define LV_ANTIALIAS 1

#define LV_VDB_SIZE (LV_HOR_RES_MAX * LV_VER_RES_MAX / 10)

#define LV_USE_GPU 0
#define LV_USE_GPU_STM32H7 0
#define LV_USE_GPU_STM32H743 0
#define LV_USE_GPU_NXP_PXP 0
#define LV_USE_GPU_NXP_VG_LITE 0

#define LV_USE_LABEL 1
#define LV_LABEL_TEXT_SEL 0
#define LV_LABEL_LONG_TXT_HINT 0

#define LV_USE_IMAGE 1

#define LV_USE_ANIMATION 1
#define LV_USE_SHADOW 1
#define LV_USE_OUTLINE 1
#define LV_USE_BLEND_MODES 1
#define LV_USE_OPA_SCALE 1

#define LV_USE_THEME_EMPTY 0
#define LV_USE_THEME_MATERIAL 1
#define LV_USE_THEME_MONO 0

#define LV_THEME_MATERIAL_DARK 0
#define LV_THEME_MATERIAL_LIGHT 1
#define LV_THEME_MATERIAL_FLAG_LIGHT 0

#define LV_USE_INESP32 0

#endif
