[env:ttgo-t-watch]
platform = espressif32
board = ttgo-t-watch
framework = arduino

monitor_speed = 115200
upload_speed = 921600

build_flags =
    -D LILYGO_WATCH_2020_V3

build_src_filter = +<*> -<data_collector.cpp>

lib_deps =
    https://github.com/Xinyuan-LilyGO/TTGO_TWatch_Library.git
    tanakamasayuki/TensorFlowLite_ESP32@^1.0.0

; ── Modo recolección de datos para entrenar red neuronal ──
[env:data-collector]
platform = espressif32
board = ttgo-t-watch
framework = arduino

monitor_speed = 115200
upload_speed = 921600

build_flags =
    -D LILYGO_WATCH_2020_V3
    -D DATA_COLLECTOR_MODE

board_build.filesystem = SPIFFS

lib_deps =
    https://github.com/Xinyuan-LilyGO/TTGO_TWatch_Library.git

build_src_filter = +<data_collector.cpp>