[env:ttgo-t-watch]
platform = espressif32
board = ttgo-t-watch
framework = arduino

; Velocidad del puerto serie para leer los datos
monitor_speed = 115200
; Velocidad de subida del código
upload_speed = 921600

; Definimos el modelo exacto (V3)
build_flags =
    -D LILYGO_WATCH_2020_V3

; Usamos el enlace directo a GitHub para evitar errores del registro
lib_deps =
    https://github.com/Xinyuan-LilyGO/TTGO_TWatch_Library.git