; ============================================================
;  ESP32-C6 2.06" Touch AMOLED  —  configuración PlatformIO
; ============================================================
;  IMPORTANTE: el platform OFICIAL de PlatformIO (espressif32)
;  se quedó en Arduino Core 2.x y NO soporta el ESP32-C6.
;  Usamos el fork de la comunidad "pioarduino", que trae
;  Arduino Core 3.x y SÍ soporta C6/C5/H2/P4.
; ============================================================

[env:esp32-c6-amoled]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.39/platform-espressif32.zip
board = esp32-c6-devkitc-1
framework = arduino
monitor_speed = 115200

; --- Serial por el USB nativo (USB-CDC) del C6 ---
build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1

monitor_filters = esp32_exception_decoder

; --- Partición grande (necesario al añadir BLE) ---
board_build.partitions = huge_app.csv

; --- Librerías ---
lib_deps =
    moononournation/GFX Library for Arduino@^1.5.0
    lewisxhe/SensorLib@^0.3.1
    lewisxhe/XPowersLib@^0.2.6

; --- Puerto serie ---
upload_port = COM6
monitor_port = COM6
